### ISSUE TITLE
 symbol _ZdlPvm, version Qt_5 not defined in file libQt5Core.so.5

### ISSUE THREAD

**Issue by LinArcX** [OneMoreGres/qtc-cppcheck#36] opened 2017-11-15 10:10 UTC
Hi. i download release 4.4 and follow your instructions. every thins is ok until open qt creator, it says:
"qtcreator: relocation error: /usr/lib/qtcreator/plugins/libQtcCppcheck.so: symbol _ZdlPvm, version Qt_5 not defined in file libQt5Core.so.5 with link time reference"
OS: Arch linux, 64bit,
Qt Creator: 4.4.1,
Qt: 5.9.2

**Comment by OneMoreGres** [comment] 2017-11-15 16:47
Hi.
Prebuilt plugin is not binary compatible with arch's qt/qtcreator.
You should recompile it from source or use qtcreator from download.qt.io.
Duplicate of #22

**Closed by OneMoreGres** 2017-11-15 16:47 UTC
